### ISSUE TITLE
publish release for Arduino Library Manager?

### ISSUE THREAD

**Issue by combs** [road-t/DM8BA10#1]
Thanks very much for making this library--it's great.

I tried to submit it to the Arduino Library Manager via their new auto-PR process, and it expects a release or tag with the same version number as in `library.properties`:
https://github.com/arduino/library-registry/pull/1024#issuecomment-1032923308

If you publish such a release or tag I can take care of following up with them about it.

Thanks!!

**Comment by road-t** [comment]
Probably I'm missing something... github reports an error when I'm trying to create a release:
`We weren’t able to create the release for you. Make sure you have a valid tag.`

**Comment by combs** [comment]
Hmm, I guess it needs a tag created in order to create a release?
https://github.com/arduino/library-registry#if-the-problem-is-with-the-library

**Comment by road-t** [comment]
I think I've managed to create a tag and publish a release.
Also I've opened a pull request: https://github.com/arduino/library-registry/pull/1026/

hope I didn't miss a lot there

**Comment by combs** [comment]
Great, thanks!
